# plugins:
# https://github.com/munter/netlify-plugin-checklinks
# - package: netlify-plugin-checklinks
# - package: netlify-plugin-image-optim
# https://github.com/munter/netlify-plugin-subfont#configuration
# - package: netlify-plugin-subfont
# https://github.com/munter/netlify-plugin-hashfiles
# - package: netlify-plugin-hashfiles
# - package: netlify-plugin-lighthouse
#   config:
#     url: "https://zachhardesty.com"

## This rule redirects to an external API, signing requests with a secret
redirects:
- from: https://zachhardesty.netlify.com/*
  to: https://zachhardesty.com/:splat
  status: 301
  force: true
- from: https://zachhardesty.netlify.app/*
  to: https://zachhardesty.com/:splat
  status: 301
  force: true
- from: /go/resume
  to: https://docs.google.com/document/d/1JluScSVuuTK9wMS2gK6ygd-4tRxCO73tvwR3lvDe1hI
